version: '3.8'

services:
  web: 
    build: .
    command: poetry run python app/manage.py runserver 0.0.0.0:8080
    volumes:
      - ./:/usr/src/app
    ports:
      - "0.0.0.0:8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
    - "127.0.0.1:5432:5432"

